title: Joey Paul
email: joeyjpaul@tamu.edu
description: Personal website of Joey Paul
baseurl: ""
url: "https://joeyjpaul23.github.io"

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
