title: Joey Paul
email: your_email@example.com
description: >-
  Computer Science student at Texas A&M University passionate about AI, data, and innovation.
baseurl: "" 
url: "https://joeypaul.github.io" 
theme: null
markdown: kramdown
include:
  - assets/css/style.css
